spring.application.name=agrosense
server.port=${PORT:9000}

spring.datasource.url=//url de la base de datos en la nube
spring.datasource.username= //usuario de la base de datos en la nube
spring.datasource.password= //contraseña de la base de datos en la nube
spring.datasource.driver-class-name=//nombredel driver de la base de datos en la nube