-- AgroSense database schema for PostgreSQL 14+.
-- Single source of truth for the tables used by backend/ and frontend/.
-- Safe to run more than once: every statement is idempotent.

CREATE TABLE IF NOT EXISTS users (
    id_user        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    last_name      VARCHAR(255) NOT NULL,
    email          VARCHAR(255) NOT NULL,
    password_hash  VARCHAR(255) NOT NULL,
    role           VARCHAR(255) NOT NULL,
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_access_at TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS estates (
    id_estate  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user    INTEGER      NOT NULL,
    name       VARCHAR(255) NOT NULL,
    location   VARCHAR(255),
    latitude   NUMERIC(10, 7),
    longitude  NUMERIC(10, 7),
    area_ha    NUMERIC(10, 2),
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_estates_user FOREIGN KEY (id_user) REFERENCES users (id_user) ON DELETE CASCADE,
    CONSTRAINT ck_estates_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_estates_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_estates_coordinates CHECK ((latitude IS NULL) = (longitude IS NULL)),
    CONSTRAINT ck_estates_area CHECK (area_ha IS NULL OR area_ha > 0)
);

CREATE TABLE IF NOT EXISTS crops (
    id_crop      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estate    INTEGER      NOT NULL,
    name         VARCHAR(255) NOT NULL,
    variety      VARCHAR(255),
    sowing_date  DATE,
    stage        VARCHAR(255) NOT NULL DEFAULT 'GERMINATION',
    humidity_min NUMERIC(5, 2),
    humidity_max NUMERIC(5, 2),
    temp_min     NUMERIC(5, 2),
    temp_max     NUMERIC(5, 2),
    ph_min       NUMERIC(4, 2),
    ph_max       NUMERIC(4, 2),
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_crops_estate FOREIGN KEY (id_estate) REFERENCES estates (id_estate) ON DELETE CASCADE,
    CONSTRAINT ck_crops_stage CHECK (stage IN
        ('GERMINATION', 'GROWTH', 'FLOWERING', 'FRUITING', 'RIPENING', 'HARVEST')),
    CONSTRAINT ck_crops_humidity CHECK (humidity_min IS NULL OR humidity_max IS NULL OR humidity_min < humidity_max),
    CONSTRAINT ck_crops_temp CHECK (temp_min IS NULL OR temp_max IS NULL OR temp_min < temp_max),
    CONSTRAINT ck_crops_ph CHECK (ph_min IS NULL OR ph_max IS NULL OR ph_min < ph_max)
);

CREATE TABLE IF NOT EXISTS sensors (
    id_sensor       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_crop         INTEGER      NOT NULL,
    sensor_code     VARCHAR(255) NOT NULL,
    sensor_type     VARCHAR(255) NOT NULL,
    location        VARCHAR(255),
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    last_reading_at TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sensors_crop FOREIGN KEY (id_crop) REFERENCES crops (id_crop) ON DELETE CASCADE,
    CONSTRAINT uq_sensors_code UNIQUE (sensor_code),
    CONSTRAINT ck_sensors_type CHECK (sensor_type IN
        ('SOIL_MOISTURE', 'AIR_TEMPERATURE', 'SOIL_TEMPERATURE', 'PH', 'CONDUCTIVITY', 'LIGHT',
         'RAIN_GAUGE', 'RELATIVE_HUMIDITY'))
);

CREATE TABLE IF NOT EXISTS sensor_readings (
    id_reading    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sensor     INTEGER        NOT NULL,
    reading_value NUMERIC(12, 4) NOT NULL,
    unit          VARCHAR(255),
    quality       VARCHAR(255) DEFAULT 'OK',
    recorded_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sensor_readings_sensor FOREIGN KEY (id_sensor) REFERENCES sensors (id_sensor) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS alerts (
    id_alert       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_crop        INTEGER      NOT NULL,
    id_sensor      INTEGER,
    alert_type     VARCHAR(255) NOT NULL,
    severity       VARCHAR(255) NOT NULL DEFAULT 'MEDIUM',
    message        VARCHAR(255) NOT NULL,
    detected_value NUMERIC(12, 4),
    acknowledged   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_alerts_crop FOREIGN KEY (id_crop) REFERENCES crops (id_crop) ON DELETE CASCADE,
    CONSTRAINT fk_alerts_sensor FOREIGN KEY (id_sensor) REFERENCES sensors (id_sensor) ON DELETE SET NULL,
    CONSTRAINT ck_alerts_type CHECK (alert_type IN
        ('LOW_HUMIDITY', 'HIGH_HUMIDITY', 'HIGH_TEMPERATURE', 'LOW_TEMPERATURE', 'PH_OUT_OF_RANGE',
         'HIGH_CONDUCTIVITY', 'PEST_DETECTED', 'RECOMMENDED_WATERING', 'WATER_STRESS')),
    CONSTRAINT ck_alerts_severity CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH'))
);

CREATE TABLE IF NOT EXISTS irrigations (
    id_irrigation   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_crop         INTEGER      NOT NULL,
    started_at      TIMESTAMP,
    ended_at        TIMESTAMP,
    duration_min    INTEGER,
    water_liters    NUMERIC(10, 2),
    irrigation_type VARCHAR(255) NOT NULL DEFAULT 'AUTOMATIC',
    activated_by    INTEGER,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_irrigations_crop FOREIGN KEY (id_crop) REFERENCES crops (id_crop) ON DELETE CASCADE,
    CONSTRAINT fk_irrigations_user FOREIGN KEY (activated_by) REFERENCES users (id_user) ON DELETE SET NULL,
    CONSTRAINT ck_irrigations_type CHECK (irrigation_type IN ('AUTOMATIC', 'MANUAL')),
    CONSTRAINT ck_irrigations_duration CHECK (duration_min IS NULL OR duration_min > 0),
    CONSTRAINT ck_irrigations_water CHECK (water_liters IS NULL OR water_liters >= 0),
    CONSTRAINT ck_irrigations_period CHECK (ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at)
);

CREATE TABLE IF NOT EXISTS ai_predictions (
    id_prediction   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_crop         INTEGER      NOT NULL,
    prediction_type VARCHAR(255) NOT NULL,
    confidence      NUMERIC(5, 4),
    recommendation  TEXT,
    model_used      VARCHAR(255),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_predictions_crop FOREIGN KEY (id_crop) REFERENCES crops (id_crop) ON DELETE CASCADE,
    CONSTRAINT ck_ai_predictions_confidence CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1)
);

-- Indexes. PostgreSQL does not index foreign keys on its own, and every query filters by owner
-- through these joins or reads the newest rows of a crop or sensor.
CREATE INDEX IF NOT EXISTS idx_estates_user ON estates (id_user);
CREATE INDEX IF NOT EXISTS idx_crops_estate ON crops (id_estate);
CREATE INDEX IF NOT EXISTS idx_sensors_crop ON sensors (id_crop);
CREATE INDEX IF NOT EXISTS idx_sensor_readings_sensor_recorded_at ON sensor_readings (id_sensor, recorded_at);
CREATE INDEX IF NOT EXISTS idx_alerts_crop_created_at ON alerts (id_crop, created_at);
CREATE INDEX IF NOT EXISTS idx_alerts_sensor ON alerts (id_sensor);
CREATE INDEX IF NOT EXISTS idx_irrigations_crop_started_at ON irrigations (id_crop, started_at);
CREATE INDEX IF NOT EXISTS idx_irrigations_activated_by ON irrigations (activated_by);
CREATE INDEX IF NOT EXISTS idx_ai_predictions_crop_created_at ON ai_predictions (id_crop, created_at);
